#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KogentCabDB")]
public partial class LINQClassDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertNewBooking(NewBooking instance);
  partial void UpdateNewBooking(NewBooking instance);
  partial void DeleteNewBooking(NewBooking instance);
  partial void InsertUser_Registration(User_Registration instance);
  partial void UpdateUser_Registration(User_Registration instance);
  partial void DeleteUser_Registration(User_Registration instance);
  #endregion
	
	public LINQClassDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KogentCabConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LINQClassDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQClassDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Feedback> Feedbacks
	{
		get
		{
			return this.GetTable<Feedback>();
		}
	}
	
	public System.Data.Linq.Table<NewBooking> NewBookings
	{
		get
		{
			return this.GetTable<NewBooking>();
		}
	}
	
	public System.Data.Linq.Table<User_Registration> User_Registrations
	{
		get
		{
			return this.GetTable<User_Registration>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feedback")]
public partial class Feedback
{
	
	private string _Comment;
	
	private string _Name;
	
	public Feedback()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this._Comment = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewBooking")]
public partial class NewBooking : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Booking_ID;
	
	private string _User_Name;
	
	private string _Pickup_City;
	
	private string _Pickup_Location;
	
	private string _Landmark;
	
	private int _Number_Of_Cabs;
	
	private string _Destination;
	
	private decimal _Contact_Number;
	
	private string _Email;
	
	private string _Pickup_Date;
	
	private string _Pickup_Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBooking_IDChanging(int value);
    partial void OnBooking_IDChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnPickup_CityChanging(string value);
    partial void OnPickup_CityChanged();
    partial void OnPickup_LocationChanging(string value);
    partial void OnPickup_LocationChanged();
    partial void OnLandmarkChanging(string value);
    partial void OnLandmarkChanged();
    partial void OnNumber_Of_CabsChanging(int value);
    partial void OnNumber_Of_CabsChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnContact_NumberChanging(decimal value);
    partial void OnContact_NumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPickup_DateChanging(string value);
    partial void OnPickup_DateChanged();
    partial void OnPickup_TimeChanging(string value);
    partial void OnPickup_TimeChanged();
    #endregion
	
	public NewBooking()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Booking_ID
	{
		get
		{
			return this._Booking_ID;
		}
		set
		{
			if ((this._Booking_ID != value))
			{
				this.OnBooking_IDChanging(value);
				this.SendPropertyChanging();
				this._Booking_ID = value;
				this.SendPropertyChanged("Booking_ID");
				this.OnBooking_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this.OnUser_NameChanging(value);
				this.SendPropertyChanging();
				this._User_Name = value;
				this.SendPropertyChanged("User_Name");
				this.OnUser_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pickup_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Pickup_City
	{
		get
		{
			return this._Pickup_City;
		}
		set
		{
			if ((this._Pickup_City != value))
			{
				this.OnPickup_CityChanging(value);
				this.SendPropertyChanging();
				this._Pickup_City = value;
				this.SendPropertyChanged("Pickup_City");
				this.OnPickup_CityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pickup_Location", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Pickup_Location
	{
		get
		{
			return this._Pickup_Location;
		}
		set
		{
			if ((this._Pickup_Location != value))
			{
				this.OnPickup_LocationChanging(value);
				this.SendPropertyChanging();
				this._Pickup_Location = value;
				this.SendPropertyChanged("Pickup_Location");
				this.OnPickup_LocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Landmark", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Landmark
	{
		get
		{
			return this._Landmark;
		}
		set
		{
			if ((this._Landmark != value))
			{
				this.OnLandmarkChanging(value);
				this.SendPropertyChanging();
				this._Landmark = value;
				this.SendPropertyChanged("Landmark");
				this.OnLandmarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_Of_Cabs", DbType="Int NOT NULL")]
	public int Number_Of_Cabs
	{
		get
		{
			return this._Number_Of_Cabs;
		}
		set
		{
			if ((this._Number_Of_Cabs != value))
			{
				this.OnNumber_Of_CabsChanging(value);
				this.SendPropertyChanging();
				this._Number_Of_Cabs = value;
				this.SendPropertyChanged("Number_Of_Cabs");
				this.OnNumber_Of_CabsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Destination
	{
		get
		{
			return this._Destination;
		}
		set
		{
			if ((this._Destination != value))
			{
				this.OnDestinationChanging(value);
				this.SendPropertyChanging();
				this._Destination = value;
				this.SendPropertyChanged("Destination");
				this.OnDestinationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_Number", DbType="Decimal(18,0) NOT NULL")]
	public decimal Contact_Number
	{
		get
		{
			return this._Contact_Number;
		}
		set
		{
			if ((this._Contact_Number != value))
			{
				this.OnContact_NumberChanging(value);
				this.SendPropertyChanging();
				this._Contact_Number = value;
				this.SendPropertyChanged("Contact_Number");
				this.OnContact_NumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pickup_Date", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Pickup_Date
	{
		get
		{
			return this._Pickup_Date;
		}
		set
		{
			if ((this._Pickup_Date != value))
			{
				this.OnPickup_DateChanging(value);
				this.SendPropertyChanging();
				this._Pickup_Date = value;
				this.SendPropertyChanged("Pickup_Date");
				this.OnPickup_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pickup_Time", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Pickup_Time
	{
		get
		{
			return this._Pickup_Time;
		}
		set
		{
			if ((this._Pickup_Time != value))
			{
				this.OnPickup_TimeChanging(value);
				this.SendPropertyChanging();
				this._Pickup_Time = value;
				this.SendPropertyChanged("Pickup_Time");
				this.OnPickup_TimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Registration")]
public partial class User_Registration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _First_Name;
	
	private string _Last_Name;
	
	private string _Sex;
	
	private string _Date_Of_Birth;
	
	private string _Email;
	
	private string _User_Name;
	
	private string _Password;
	
	private string _Password_Hint;
	
	private string _Address;
	
	private string _State;
	
	private string _City;
	
	private System.Nullable<int> _PIN_Code;
	
	private decimal _Contact_Number;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnDate_Of_BirthChanging(string value);
    partial void OnDate_Of_BirthChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPassword_HintChanging(string value);
    partial void OnPassword_HintChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnPIN_CodeChanging(System.Nullable<int> value);
    partial void OnPIN_CodeChanged();
    partial void OnContact_NumberChanging(decimal value);
    partial void OnContact_NumberChanged();
    #endregion
	
	public User_Registration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string First_Name
	{
		get
		{
			return this._First_Name;
		}
		set
		{
			if ((this._First_Name != value))
			{
				this.OnFirst_NameChanging(value);
				this.SendPropertyChanging();
				this._First_Name = value;
				this.SendPropertyChanged("First_Name");
				this.OnFirst_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Last_Name
	{
		get
		{
			return this._Last_Name;
		}
		set
		{
			if ((this._Last_Name != value))
			{
				this.OnLast_NameChanging(value);
				this.SendPropertyChanging();
				this._Last_Name = value;
				this.SendPropertyChanged("Last_Name");
				this.OnLast_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Sex
	{
		get
		{
			return this._Sex;
		}
		set
		{
			if ((this._Sex != value))
			{
				this.OnSexChanging(value);
				this.SendPropertyChanging();
				this._Sex = value;
				this.SendPropertyChanged("Sex");
				this.OnSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Birth", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Date_Of_Birth
	{
		get
		{
			return this._Date_Of_Birth;
		}
		set
		{
			if ((this._Date_Of_Birth != value))
			{
				this.OnDate_Of_BirthChanging(value);
				this.SendPropertyChanging();
				this._Date_Of_Birth = value;
				this.SendPropertyChanged("Date_Of_Birth");
				this.OnDate_Of_BirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this.OnUser_NameChanging(value);
				this.SendPropertyChanging();
				this._User_Name = value;
				this.SendPropertyChanged("User_Name");
				this.OnUser_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_Hint", DbType="NVarChar(50)")]
	public string Password_Hint
	{
		get
		{
			return this._Password_Hint;
		}
		set
		{
			if ((this._Password_Hint != value))
			{
				this.OnPassword_HintChanging(value);
				this.SendPropertyChanging();
				this._Password_Hint = value;
				this.SendPropertyChanged("Password_Hint");
				this.OnPassword_HintChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN_Code", DbType="Int")]
	public System.Nullable<int> PIN_Code
	{
		get
		{
			return this._PIN_Code;
		}
		set
		{
			if ((this._PIN_Code != value))
			{
				this.OnPIN_CodeChanging(value);
				this.SendPropertyChanging();
				this._PIN_Code = value;
				this.SendPropertyChanged("PIN_Code");
				this.OnPIN_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_Number", DbType="Decimal(18,0) NOT NULL")]
	public decimal Contact_Number
	{
		get
		{
			return this._Contact_Number;
		}
		set
		{
			if ((this._Contact_Number != value))
			{
				this.OnContact_NumberChanging(value);
				this.SendPropertyChanging();
				this._Contact_Number = value;
				this.SendPropertyChanged("Contact_Number");
				this.OnContact_NumberChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
